//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENT()
        {
            this.AGENT_ACCOUNT = new HashSet<AGENT_ACCOUNT>();
        }
    
        public string Agent_ID { get; set; }
        public string Agent_Name { get; set; }
        public string Agent_Address { get; set; }
        public string Agent_Email { get; set; }
        public string Agent_Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENT_ACCOUNT> AGENT_ACCOUNT { get; set; }
    }
}
