//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOOD_DELIVERY
    {
        public string Good_Delivery_ID { get; set; }
        public string Transaction_ID { get; set; }
        public string Accountant_ID { get; set; }
        public string OrderList_ID { get; set; }
        public Nullable<System.DateTime> Date_Created_Good_Delivery { get; set; }
    
        public virtual ACCOUNTANT ACCOUNTANT { get; set; }
        public virtual ORDER_LIST ORDER_LIST { get; set; }
        public virtual TRANSACTION TRANSACTION { get; set; }
    }
}
