//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_LIST_DETAILS
    {
        public string Product_ID { get; set; }
        public string OrderList_ID { get; set; }
        public Nullable<int> Quantities { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<decimal> Total_Money { get; set; }
        public Nullable<int> Remain_Quantities { get; set; }
    
        public virtual MOBILE_PRODUCT MOBILE_PRODUCT { get; set; }
        public virtual ORDER_LIST ORDER_LIST { get; set; }
    }
}
