//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_DETAILS
    {
        public string Receipt_ID { get; set; }
        public string Product_ID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantities { get; set; }
    
        public virtual MOBILE_PRODUCT MOBILE_PRODUCT { get; set; }
        public virtual WAREHOUSE_RECEIPT WAREHOUSE_RECEIPT { get; set; }
    }
}
