//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACTION()
        {
            this.GOOD_DELIVERY = new HashSet<GOOD_DELIVERY>();
        }
    
        public string Transaction_ID { get; set; }
        public string PaymentMethod_ID { get; set; }
        public Nullable<System.DateTime> Date_Created_Transaction { get; set; }
        public string Status_Transaction { get; set; }
        public string Invoice_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOOD_DELIVERY> GOOD_DELIVERY { get; set; }
        public virtual INVOICE INVOICE { get; set; }
        public virtual PAYMENT_METHOD PAYMENT_METHOD { get; set; }
    }
}
