//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE_RECEIPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAREHOUSE_RECEIPT()
        {
            this.RECEIPT_DETAILS = new HashSet<RECEIPT_DETAILS>();
        }
    
        public string Receipt_ID { get; set; }
        public string Accountant_ID { get; set; }
        public Nullable<System.DateTime> Date_Created_Receipt { get; set; }
        public string Driver_Name { get; set; }
        public string WareHouse_Address { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual ACCOUNTANT ACCOUNTANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT_DETAILS> RECEIPT_DETAILS { get; set; }
    }
}
